### ISSUE TITLE
请问, 这是怎么启动的, 是只要填一个cookie就行么?

### ISSUE THREAD

**Issue by DancingLeaf123** [zc2638/ddshop#1]

**Comment by DancingLeaf123** [comment]
以及, 目前很多账号似乎已经被风控了, 不知道还能不能下单

**Comment by zc2638** [comment]
1. 提前将需要购买的商品加到购物车
2. 在抢购前，执行此程序，只需要一个用户cookie即可
3. 查看响应日志

<img width="827" alt="image" src="https://user-images.githubusercontent.com/28284116/162657917-d851b246-199c-44f6-aa76-7422e4dd081e.png">
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/28284116/162657948-565c8484-812c-4086-8d89-6e9e4b51e8df.png">
<img width="923" alt="image" src="https://user-images.githubusercontent.com/28284116/162657983-025302b6-a80a-47bc-b13c-e718b2d554f6.png">

**Comment by funnyData** [comment]
ReserveTime 很容易出现405，感觉验证逻辑改了。

**Comment by zc2638** [comment]
@funnyData 可以把日志截个图吗

**Comment by vividelephant** [comment]
![image](https://user-images.githubusercontent.com/46945051/162676069-e5a7ac27-337f-4568-8f56-c28b5c6c2fd6.png)

**Comment by zc2638** [comment]
可以参考 #4  
@funnyData
