### ISSUE TITLE
能不能加个微信的推送

### ISSUE THREAD

**Issue by M-a-s-a-t-o** [zc2638/ddshop#12]
比如pushplus

**Comment by haifengzuishuai** [comment]
二开加个bark的系统推送，应该不是太难

**Comment by zc2638** [comment]
抢到了之后播放音乐，应该比微信推送更直接把

**Comment by wyk930826** [comment]
自己加个发给back或者server酱有那么困难吗

**Comment by M-a-s-a-t-o** [comment]
> 抢到了之后播放音乐，应该比微信推送更直接把
在Linux服务器上跑的

**Comment by zc2638** [comment]
已经支持 Bark 通知，暂时没有计划支持其它方式。
如果有其他通知需求，可以尝试贡献一下。
