### ISSUE TITLE
Error: 获取用户信息失败: 无法识别的状态码: {"success":false,"code":9007,"message":"您的访问已过期","data":{"is_china_mobile":1}}

### ISSUE THREAD

**Issue by qishu321** [zc2638/ddshop#13]
这个怎么解决啊？
Error: 获取用户信息失败: 无法识别的状态码: {"success":false,"code":9007,"message":"您的访问已过期","data":{"is_china_mobile":1}}

**Comment by M-a-s-a-t-o** [comment]
重新抓包就行了，你在PC小程序抓的包，然后在手机小程序登录了，就会把原来的ck挤掉

**Comment by qishu321** [comment]
> 抓紧抓包就行了，你在PC小程序抓的包，然后在手机小程序登录了，把原本的ck包挤掉

但是我的ck是在手机上抓到的呀，这个是只支持pc小程序吗？

**Comment by zc2638** [comment]
程序运行 使用小程序的cookie，手机上建议使用app操作

**Comment by qishu321** [comment]
> 程序运行 使用小程序的cookie，手机上建议使用app操作

搞定了，太感谢了
