### ISSUE TITLE
可否增加功能或者告知如何直接确定地址和支付方式，以避免手工干预选择？

### ISSUE THREAD

**Issue by cleanykl** [zc2638/ddshop#17]
谢谢！

**Comment by zc2638** [comment]
地址只能进行模糊匹配，可能会导致多条地址匹配成功

**Comment by M-a-s-a-t-o** [comment]
linux可以这么写，就会默认选择第一个选项
masato@server:~$ yes '' | ./ddshop --cookie ***************

**Comment by cleanykl** [comment]
能不能把获取到的地址放到一个固定的表格里，这样获取一次我就知道我想送的地址排第几了，然后我可以手工改个变量，写死它。

**Comment by cleanykl** [comment]
主要是因为想避免六点自动运行，可是却还是需要起来选地址，选付款方式。。。

**Comment by zc2638** [comment]
已支持

**Comment by cleanykl** [comment]
通过变量直接决定支付方式有了，多个地址的话，是不是只能留一个才能成为默认值？有没有一个诸如 --address 1 的参数？

**Comment by zc2638** [comment]
是的，只留一个才能默认，指定`--address 1`可能会发生实际获取匹配到的地址不符
