### ISSUE TITLE
 >>> 获取购物车中有效商品 ERROR  [2022/04/13 11:41:10] 检查购物车失败: 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-13 11:41:10"}

### ISSUE THREAD

**Issue by lzz0810** [zc2638/ddshop#18]
下了新版就报错如题，之前没有的

**Comment by zc2638** [comment]
cookie失效了，重新获取小程序版的cookie

**Comment by lzz0810** [comment]
感谢，可以了。另外请问提交订单(2022/04/13 14:30:00——2022/04/13 22:30:00)失败: 无法识别的状态码: {"success":false,"code":-1,"msg":"操作失败",是啥原因😭

**Comment by M-a-s-a-t-o** [comment]
0.06版用APP版cookie有同样的问题，同一个cookie用0.02版就没有问题
0.06版改用小程序版cookie就没问题了

**Comment by lzz0810** [comment]
> 

谢谢，请问一下提交订单时返回 失败: 无法识别的状态码: {"success":false,"code":-1,"msg":"操作失败",是啥原因引起的

**Comment by zc2638** [comment]
@lzz0810 见 #21
