### ISSUE TITLE
账号成功被封 T_T 

### ISSUE THREAD

**Issue by yisier** [zc2638/ddshop#19]
![image](https://user-images.githubusercontent.com/26956516/163108633-7e6aa393-1190-4e3e-9695-775363eaec30.png)

购物车直接加载不出来 ，同一个网络下的另外一个手机可以正常显示，小程序 和 app端都是这样子

**Comment by M-a-s-a-t-o** [comment]
这么快就被封了？你运行了多久？有没有换个ip试试？

**Comment by zc2638** [comment]
抓个包看看，接口返回什么内容

**Comment by cleanykl** [comment]
这个情况下，手机重启一下基本上就好了。至少我昨天碰到这个情况重启了一下手机，重新进入app，或者小程序，都恢复了。

**Comment by mztian** [comment]
用手机和小程序，购物车直接不加载，这是被封号了么

**Comment by mztian** [comment]
> 抓个包看看，接口返回什么内容

封号手机加载不出购物车，抓包返回以下内容
{"error":"AssertError","code":"405","data":"-405"}

更新：过了段时间好了，又能刷新出来了

**Comment by reverse-Man** [comment]
这不是账号封了，多刷下就出来了

**Comment by yisier** [comment]
https://github.com/zc2638/ddshop/blob/d6e9a126b0ffea04db75bdddac318554cb1acddf/cmd/ddshop/app/app.go#L79

这个地方出现405要加个休眠，我电脑挂着刷了一夜405，第二天账号被限制了。不过现在已经恢复了，购物车可以正常打开

**Comment by ROCKBUND** [comment]
今天捡漏抢到一单，去手机付款提示：同一时段下单人数过多，请稍候尝试。付不了钱。。。
我估计也是黑号了

**Comment by zc2638** [comment]
#37

**Comment by meimxn** [comment]
> 

我跟你遇到相同情况，后来怎么处理了呢
