### ISSUE TITLE
确定有货，但是一直下单失败

### ISSUE THREAD

**Issue by reverse-Man** [zc2638/ddshop#21]
提交订单(2022/04/13 16:07:29——2022/04/13 22:30:00)失败: 无法识别的状态码: {"success":false,"code":-1,"msg":"操作失败","data":{"station_id":"5c2f3b00716de13e768b9cbe","tradeTag":"interError"},"tradeTag":"interError","server_time":1649836949,"is_trade":1}

但我手工进去却下单成功了

**Comment by lzz0810** [comment]
+1

**Comment by zc2638** [comment]
更新了好像有变动，新的版本正在测试

**Comment by zc2638** [comment]
尝试 `v0.0.7` 版本，刚刚测试通过

**Comment by lzz0810** [comment]
> 
谢谢，可以下单成功，只有无法识别的状态码: {"success":false,"code":5003,"msg":"操作太频繁, 请返回购物车稍后重试。"

**Comment by zc2638** [comment]
下单成功就好。因为是并发请求，所以输出的内容顺序会有些问题。
