### ISSUE TITLE
直接执行go时出现以下报错

### ISSUE THREAD

**Issue by wrc1993** [zc2638/ddshop#22]
root@iZbp17xlwhqgtqvcszh6kzZ:~/test/ddshop# go run cmd/ddshop/main.go 
build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element

抱歉，本人非做go。对go的包机制不是很懂，请问这个需要怎么解决呢？

**Comment by zc2638** [comment]
使用 go1.17+
