### ISSUE TITLE
-3100 无法识别的状态码

### ISSUE THREAD

**Issue by MrRumpel** [zc2638/ddshop#25]
![DQ NCI@F}(3FW MV17U_C6](https://user-images.githubusercontent.com/20477534/163278346-d8e39356-80fb-4de8-a7d2-c1ee29dbb291.png)

**Comment by reverse-Man** [comment]
一样的，全部下单失败了

早上打开小程序的时候发现更新了，就猜到又改东西了

**Comment by SoberY** [comment]
ERROR  [2022/04/14 07:54:46] 全选购物车商品失败: 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-14 07:54:43"}
是因为小程序更新了嘛, 加了什么验证?

**Comment by M-a-s-a-t-o** [comment]
INFO   [2022/04/14 08:30:02] =====> 获取可预约时间
INFO   [2022/04/14 08:30:02] 发现可用的配送时段!
INFO   [2022/04/14 08:30:02] =====> 生成订单信息
ERROR  [2022/04/14 08:30:02] 检查订单失败: 无法识别的状态码: {     "success": false,     "code": -3100,     "msg": "",     "tips": {         "duration": 400,         "limitMsg": "当
前页面拥挤，部分数据加载失败",         "loadingMsg": "数据加载中，请稍等...",         "loadErrorMsg": "加载失败，请重新尝试"      },     "data": {} }

**Comment by MrRumpel** [comment]
> ERROR [2022/04/14 07:54:46] 全选购物车商品失败: 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-14 07:54:43"} 是因为小程序更新了嘛, 加了什么验证?

这个应该是你cookies过期了。重新抓包获取下

**Comment by SoberY** [comment]
> > ERROR [2022/04/14 07:54:46] 全选购物车商品失败: 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-14 07:54:43"} 是因为小程序更新了嘛, 加了什么验证?
> 
> 这个应该是你cookies过期了。重新抓包获取下

抓的app的包, cookie好像有限制? 换小程序的就可以了, 3100好像不影响下单 换个有货的城市下单流程好像没问题

**Comment by zc2638** [comment]
尝试使用新版本，已经过滤3100错误

**Comment by M-a-s-a-t-o** [comment]
所以下单失败并不是3100的问题？应该是接口限流了吧

**Comment by M-a-s-a-t-o** [comment]
![image](https://user-images.githubusercontent.com/42001748/163318694-f3763809-2adc-44fb-9641-4a33c0abe398.png)
总算成功抢到一单
