### ISSUE TITLE
无法识别的状态码，用的是010版本

### ISSUE THREAD

**Issue by zijianziye** [zc2638/ddshop#33]
WARNING[2022/04/15 05:58:04] 将在 100ms 后重试
WARNING[2022/04/15 05:58:04] 部分数据加载失败: {     "success": false,     "code": -3100,     "msg": "",     "tips": {         "duration": 400,         "limitMsg": "当前页面拥挤，部分数据加载失败",         "loadingMsg": "数据加载中，请稍等...",         "loadErrorMsg": "加载失败，请重新尝试"      },     "data": {} }
WARNING[2022/04/15 05:58:04] 将在 100ms 后重试
WARNING[2022/04/15 05:58:05] 部分数据加载失败: {     "success": false,     "code": -3100,     "msg": "",     "tips": {         "duration": 400,         "limitMsg": "当前页面拥挤，部分数据加载失败",         "loadingMsg": "数据加载中，请稍等...",         "loadErrorMsg": "加载失败，请重新尝试"      },     "data": {} }
WARNING[2022/04/15 05:58:05] 将在 100ms 后重试
WARNING[2022/04/15 05:58:05] 部分数据加载失败: {     "success": false,     "code": -3100,     "msg": "",     "tips": {         "duration": 400,         "limitMsg": "当前页面拥挤，部分数据加载失败",         "loadingMsg": "数据加载中，请稍等...",         "loadErrorMsg": "加载失败，请重新尝试"      },     "data": {} }
WARNING[2022/04/15 05:58:05] 将在 100ms 后重试
ERROR  [2022/04/15 05:58:05] 检查订单失败: 无法识别的状态码: {"msg":"系统异常","code":1,"timestamp":"2022-04-15 05:58:23","success":false,"exec_time":null}

**Comment by zijianziye** [comment]
WARNING[2022/04/15 06:16:25] 将在 100ms 后重试
WARNING[2022/04/15 06:16:25] 当前人多拥挤(-3001): {     "success": false,       "code": -3001,  "msg": "",      "tips": {               "duration": 400,                "limitMsg": "前方拥挤，请稍后再试..."   },      "data": {} }
WARNING[2022/04/15 06:16:25] 将在 100ms 后重试
WARNING[2022/04/15 06:16:25] 提交订单(2023/03/30 05:00:00——2023/03/30 23:00:00)失败: 无法识别的状态码: {"success":false,"code":-1,"msg":"操作失败","data":{"tradeTag":"interError"},"tradeTag":"interError","server_time":1649974602,"is_trade":1}
WARNING[2022/04/15 06:16:25] 当前人多拥挤(-3001): {     "success": false,       "code": -3001,  "msg": "",      "tips": {               "duration": 400,                "limitMsg": "前方拥挤，请稍后再试..."   },      "data": {} }

补充，好像订单时间有问题

**Comment by zijianziye** [comment]
抓包现在APPVERSION已经是2.82.4，目前账号已经出现问题

**Comment by fengziadmin** [comment]
> 抓包现在APPVERSION已经是2.82.4，目前账号已经出现问题

你账号出现了啥问题？

**Comment by zc2638** [comment]
@zijianziye 哪儿个区的，怀疑对站点增加了限制

**Comment by SayHelloGsx** [comment]
> @zijianziye 哪儿个区的，怀疑对站点增加了限制

我这也有 闵行区的

**Comment by HisaacH** [comment]
> 
我这也有，闵行漕河泾附近

**Comment by zc2638** [comment]
可能和 #37 有关？可以尝试下
