### ISSUE TITLE
账号估计被封

### ISSUE THREAD

**Issue by zijianziye** [zc2638/ddshop#35]
目前能加入购物车，能从购物车转到结算页面，选择地址永远都是：前方拥挤，请稍后再试，而且无法选择支付方式（只有微信），无法正常通过APP下单

**Comment by zijianziye** [comment]
用工具也永远都是
WARNING[2022/04/15 06:55:26] 当前人多拥挤(-3001): {"success": false,"code": -3001,"msg": "","tips": {"duration": 400,"limitMsg": "前方拥挤，请稍后再试..."},"data": {}}

**Comment by zc2638** [comment]
不要刷的太频繁，尽量在抢之前开一下就行。  
被封的特征：定位到其它城市也无法下单。

**Comment by zc2638** [comment]
#37
