### ISSUE TITLE
账号可能被封的情况说明

### ISSUE THREAD

**Issue by zc2638** [zc2638/ddshop#37]
**判断情况：**

1. 尝试添加一个其它城市的地址，也无法正常下单

**解决方法：**
1. 打电话客服 或 联系在线客户，反应无法下单的问题

有其他情况，可添加补充

**Comment by reverse-Man** [comment]
已经成功被禁了。2个号切到别的城市也没法下单。这是因为发包太猛了吗？

**Comment by M-a-s-a-t-o** [comment]
我也被封了，表现为获取不到预约时间，换了城市和IP也一样

**Comment by zijianziye** [comment]
切换其他城市没同样刷新不出配送时间，我的帖子里当初获取的下单时间是2023年

**Comment by zc2638** [comment]
@zijianziye 参考 #36

**Comment by zijianziye** [comment]
我有两个号，不过一个是前几天被封的，用的是JAVA跑的，改了包量，那个号彻底废了，不能把任何东西加入购物车。
今天被封的，是无法下单，获取不了配送时间，切换城市 IP都一样

**Comment by zijianziye** [comment]
目前新情况。
早上被封的号和之前的号一样了，无法加入购物车。抓包405，ASSERERROR

**Comment by SoberY** [comment]
频繁访问购物车页面会导致封禁, 但是提单页好像不会, 这两个页面的 retry_count 是不是应该单独设置一下, 把retry_count调大的话会并发请求提单页一下就被ban了

**Comment by JerryZheng89** [comment]
被封了, 用的是最新版本,  是在11点多空闲时间内跑的程序, 正在通过在线客服沟通
之前也在空亲时间内跑过的, 没有出现问题, 可能最近dd 更新了封号策略, 建议加强随机访问的机制
