### ISSUE TITLE
好像有bug会从0点01秒开始执行

### ISSUE THREAD

**Issue by SayHelloGsx** [zc2638/ddshop#38]
![日志](https://user-images.githubusercontent.com/36391162/163506449-d058b9e6-4777-4107-8d13-ac1db1e88118.png)
![配置](https://user-images.githubusercontent.com/36391162/163506467-e1f2a15f-ecf9-4be7-910f-af0a6d793d8e.png)
配置使用的是默认的两个时间点，但是docker日志上面显示了，第二天0点1秒开始自动执行了

**Comment by aimuz** [comment]
逻辑应该有点问题
https://github.com/zc2638/ddshop/blob/c50125ae6855de2ecb8fea6ff47b94c6ae6c1891/core/session.go#L130-L162

**Comment by zc2638** [comment]
fixed
