### ISSUE TITLE
当前人多拥挤(-3000): {"success":false,"code":-3000,"msg":"当前人多拥挤，请稍后尝试刷新页面","data": []}

### ISSUE THREAD

**Issue by qishu321** [zc2638/ddshop#39]
当前人多拥挤(-3000): {"success":false,"code":-3000,"msg":"当前人多拥挤，请稍后尝试刷新页面","data": []}这个怎么办啊

**Comment by zc2638** [comment]
不影响，和平时点不出购物车一样，因为请求量太大，入口有限流

**Comment by qishu321** [comment]
> 不影响，和平时点不出购物车一样，因为请求量太大，入口有限流

我是被拉黑了，因为我在下午不忙的时候看，也是这样的

**Comment by zc2638** [comment]
#37
