### ISSUE TITLE
请问一下cookie填在哪吗，没有找到config

### ISSUE THREAD

**Issue by vividelephant** [zc2638/ddshop#4]
感谢

**Comment by Amadeus-1048** [comment]
他这个是执行程序
你在linux上就是 ./文件名 --cookie "你的cookie"
在windows上就是 .\文件名.exe --cookie "你的cookie"

**Comment by vividelephant** [comment]
完美执行 但是出现405是什么情况。佬

**Comment by Amadeus-1048** [comment]
啊这... 那我就不知道了，可能是流传的被风控了。我这里执行是正常的，可能是前几天你用别的程序刷太多了。
![image](https://user-images.githubusercontent.com/71281730/162675987-329e8ca9-8a52-4c48-a3a8-6d4578aa8e56.png)

**Comment by vividelephant** [comment]
啊这。。我换个号。感谢

**Comment by vividelephant** [comment]
![image](https://user-images.githubusercontent.com/46945051/162676340-d9475ed9-0f38-42e8-8446-25170e382ea6.png)
hen很离谱

**Comment by zc2638** [comment]
执行开始，用户的id有获取到吗，应该会打印出来。  
如果截图的话，请记得把 id 和 cookie 部分打码。  
@vividelephant

**Comment by vividelephant** [comment]
![image](https://user-images.githubusercontent.com/46945051/162677076-a57af067-a24b-4af0-bf23-1c8a14c206f0.png)
有的，但是很可能我前两天用了别的程序
@zc2638

**Comment by zc2638** [comment]
@vividelephant 
在叮咚微信小程序可以提交订单吗？ 
可以的话，可以抓包把请求 邮件发我，我看看能不能解决这个问题

**Comment by vividelephant** [comment]
@zc2638 
佬，已发。
我这个抓包软件没法打包，我手动一个个保存的。凑活看，，

**Comment by zc2638** [comment]
@vividelephant  你有用微信小程序登陆过吗，这个cookie是手机app的？

**Comment by vividelephant** [comment]
对 是app的。没有登过小程序？我用小程序抓包跑下？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zc2638/ddshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月11日(星期一) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zc2638/ddshop] 请问一下cookie填在哪吗，没有找到config (Issue #4)





 
@vividelephant  你有用微信小程序登陆过吗，这个cookie是手机app的？

**Comment by zc2638** [comment]
@vividelephant 恩，你试一下。理论上应该没什么问题。

**Comment by vividelephant** [comment]
@zc2638 小程序cookie可以 完全没问题
