### ISSUE TITLE
刚刚用的0.02版，APP的CK，竟然抢到了

### ISSUE THREAD

**Issue by M-a-s-a-t-o** [zc2638/ddshop#40]
看来只能靠闲时捡漏了，6点和8点半不但抢不到还会被封账号

**Comment by LeiWangJava** [comment]
老哥，闲时一直很挂着，不会封号吗？另外问一下，你那边时商品没货，但是有配送时间安排，还是商品有货，但是没有配送时间安排啊

**Comment by M-a-s-a-t-o** [comment]
下午一两点有货没运力的情况下挂着，没挂多久就抢到了，连着两天都抢到

**Comment by LeiWangJava** [comment]
老哥有找到美团买菜的类似这样的代码吗？我找的全是autojs的脚本，没有这个有效率，我这边叮咚也是一直没有货，，只有美团有货

**Comment by M-a-s-a-t-o** [comment]
美团买菜没有，这不都等着作者大佬写么

**Comment by nereus-east** [comment]
没运力也能抢到是因为有人退单了吗？

**Comment by yeyuchen198** [comment]
> 老哥，闲时一直很挂着，不会封号吗？另外问一下，你那边时商品没货，但是有配送时间安排，还是商品有货，但是没有配送时间安排啊

我之前试过白天一直挂着，10s左右间隔轮询预约时间和购物车，后面次数多了会被限制，返回405。不过账号没被封，还是可以下单的
