### ISSUE TITLE
抓包是最新的Cookie,用户信息和收货地址都获取到了，获取购物车中的有效商品时返回访问过期重新登陆

### ISSUE THREAD

**Issue by MyPuppet** [zc2638/ddshop#42]
如题
去定Cookie是最新的，每次都可以获取到用户ID名称和收货地址
以下为输出结果：

? 请选择支付方式 微信
INFO   [2022/04/15 21:38:07] 已选择支付方式：微信

INFO   [2022/04/15 21:38:07] =====> 获取购物车中有效商品
WARNING[2022/04/15 21:38:07] 尝试次数: 1, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:07"}
WARNING[2022/04/15 21:38:07] 尝试次数: 2, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:07"}
WARNING[2022/04/15 21:38:07] 尝试次数: 3, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:07"}
WARNING[2022/04/15 21:38:07] 尝试次数: 4, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:07"}
WARNING[2022/04/15 21:38:07] 尝试次数: 5, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:07"}
WARNING[2022/04/15 21:38:07] 尝试次数: 6, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:08"}
WARNING[2022/04/15 21:38:08] 尝试次数: 7, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:07"}
WARNING[2022/04/15 21:38:08] 尝试次数: 8, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-15 21:38:07"}

**Comment by LeiWangJava** [comment]
我刚刚也是这样，重启了一下docker就好了

**Comment by zc2638** [comment]
Cookie是App的还是小程序的？
@MyPuppet

**Comment by MyPuppet** [comment]
> Cookie是App的还是小程序的？ @MyPuppet

APP的，IOS版本

**Comment by zc2638** [comment]
程序默认以小程序方式运行，所以Cookie需要小程序的。
后面加个 App 的支持
@MyPuppet

**Comment by nereus-east** [comment]
same issue, 我也是IOS的cookie

**Comment by zc2638** [comment]
已支持
