### ISSUE TITLE
叮咚加入了封号的逻辑

### ISSUE THREAD

**Issue by jasonyzi** [zc2638/ddshop#43]
今天试了好几个号，发现叮咚对不同的账号做了不同限制，具体如下：
新注册账号或提交次数正常的账号，可以顺利进入结算界面，并打开配送时间；
提交次数较多的，在上海的地址只能进入结算，打不开配送时间，但是在别的城市可以正常下单；
提交次数极多的，没有用脚本的，出现重新加载界面，偶尔可以进入结算，很难打开配送时间，但是在别的城市可以下单。
提交次数超级超级多，用脚本的，直接购物车空白，或者重新加载界面，别的城市也无法下单，就是封号了！

**Comment by LeiWangJava** [comment]
我账号应该被风控了，能打开购物车界面，配送时间无法打开，一直处于拥挤中，换别的城市依旧如此

**Comment by jasonyzi** [comment]
我也是，完全无法使用！已经去投诉了> 我账号应该被风控了，能打开购物车界面，配送时间无法打开，一直处于拥挤中，换别的城市依旧如此

**Comment by LeiWangJava** [comment]
投诉能解决？？我20分钟前刚被封的，我明天再投诉吧

**Comment by jasonyzi** [comment]
你去看看新浪投诉，都是一样的问题，先投诉了再说！

**Comment by dyxushuai** [comment]
我修改了一下代码，在重试间隔和次数上加了一个很大的随机浮动 稍后试试效果

**Comment by jasonyzi** [comment]
那得看叮咚封号的逻辑是什么了，按小时算还是按分钟算总次数，直接BBQ

**Comment by Tony-KeX** [comment]
> 我修改了一下代码，在重试间隔和次数上加了一个很大的随机浮动 稍后试试效果

我尝试了每五分钟尝试运行-30～30s的时间间隔，在这一分钟内每隔一个随机数的时间（15s左右）查询一次购物车没被封

**Comment by LeiWangJava** [comment]
已经被封了的人，看你们秀，（羡慕）

**Comment by Tony-KeX** [comment]
但是下一步查询运力的时候时间间隔也不可能改得像查购物车一样，不然就跟没开一样

**Comment by LeiWangJava** [comment]
获取购物车信息  {"error":"AssertError","code":"405","data":"-405"}   焯

**Comment by Tony-KeX** [comment]
> 已经被封了的人，看你们秀，（羡慕）

我有一天抢了三单，晚上00:00:00抢到了，后来就被封了，好在送到了

**Comment by Tony-KeX** [comment]
> 获取购物车信息 {"error":"AssertError","code":"405","data":"-405"} 焯

尝试client id改成3

**Comment by LeiWangJava** [comment]
牛逼，client id改成3  解决了购物车 405问题，下一步就是配送时间拥挤了

**Comment by LeiWangJava** [comment]
配送时间获取     {"success":false,"code":-3000,"msg":"当前人多拥挤，请稍后尝试刷新页面","data": []}    ，大佬，再指点一下..

**Comment by Tony-KeX** [comment]
> 配送时间获取 {"success":false,"code":-3000,"msg":"当前人多拥挤，请稍后尝试刷新页面","data": []} ，大佬，再指点一下..

这个应该没办法了，换号吧，隔一天这个问题应该就没了

**Comment by LeiWangJava** [comment]
okk，明天用autojs试试美团看有没有戏

**Comment by yanjinbin** [comment]
有抢到的兄弟没

**Comment by jasonyzi** [comment]
准备静默几天

**Comment by M-a-s-a-t-o** [comment]
昨天被封的号今天貌似解封了

**Comment by SnoopyGo** [comment]
> > 配送时间获取 {"success":false,"code":-3000,"msg":"当前人多拥挤，请稍后尝试刷新页面","data": []} ，大佬，再指点一下..
> 
> 这个应该没办法了，换号吧，隔一天这个问题应该就没了

请问一下，今天第一单抢到了但是付款的时候一直显示：抱歉，同一时间下单人数过多，建议您稍后再试 。这个是被封号了吗？

**Comment by jasonyzi** [comment]
是的

**Comment by SnoopyGo** [comment]
请问有办法解决吗？我换到其他省份地址，可以提交订单也可以付款。裂开
