### ISSUE TITLE
正确的cookie，但是报这个错误

### ISSUE THREAD

**Issue by wrc1993** [zc2638/ddshop#44]
WARNING[2022/04/16 06:03:51] 尝试次数: 38, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 37, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 36, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 35, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 34, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 33, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 32, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 31, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 30, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 29, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 28, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 27, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 26, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 25, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 24, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 23, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"} 
WARNING[2022/04/16 06:03:51] 尝试次数: 22, 无法识别的状态码: {"code":1111,"msg":"您的访问已过期,请重新登录","success":false,"timestamp":"2022-04-16 06:03:50"}

**Comment by zc2638** [comment]
同 #42

**Comment by zc2638** [comment]
已支持 app 通道
