### ISSUE TITLE
有没有抢到的  来这里报个到兄弟们 

### ISSUE THREAD

**Issue by yanjinbin** [zc2638/ddshop#45]
😭 还没帮我朋友抢到

**Comment by M-a-s-a-t-o** [comment]
#40
#25

**Comment by yeyuchen198** [comment]
高峰期抢不到。可以提前把时间参数和购物车信息配置好，准点直接发起addNewOrder请求，频繁请求甚至开多线程同时请求，会405限制甚至封号。（可预约的时候，可以买酒测试，看看能不能走通）

捡漏或许可用。我试过白天闲时一直以10s左右的间隔获取可预约时间列表和查询购物车，次数多了也会报405，但没被封号，后来还手抢了一单
![mmexport1650166125667](https://user-images.githubusercontent.com/89305403/163699333-fd2cfdae-3800-4e5b-b5d8-585c11a77b1e.png)
![mmexport1650166129714](https://user-images.githubusercontent.com/89305403/163699340-2c83d31c-5bc4-416e-816d-ae62fce77655.png)

**Comment by yanjinbin** [comment]
我发现热门紧俏商品还是很难抢的
