### ISSUE TITLE
bark key指的是那个啊 能不能指下路哦

### ISSUE THREAD

**Issue by yanjinbin** [zc2638/ddshop#47]
rt

**Comment by cjxlol** [comment]
就是这一串
<img width="338" alt="image" src="https://user-images.githubusercontent.com/8966078/163681322-b01581ca-b404-4829-b229-f40eab25c49c.png">

**Comment by ben0112** [comment]
@zc2638 能不能加一个自建bark服务器的参数？

**Comment by zc2638** [comment]
@ben0112 已支持
