### ISSUE TITLE
求推荐个golang进阶路线

### ISSUE THREAD

**Issue by yuebaix** [zc2638/ddshop#49]
码主是哪个公司的啊，也想混进istio圈子，需要达到什么水平？求个攻略路线

**Comment by zc2638** [comment]
你现在了解到什么程度呢

**Comment by yuebaix** [comment]
> 你现在了解到什么程度呢

大概就是golang语法+gin+gorm+viper+cobra+zap+embed+template这样吧，后续提升需要学啥才能找个公司上班呢？

**Comment by zc2638** [comment]
准备以后往什么方向发展？

**Comment by yuebaix** [comment]
> 准备以后往什么方向发展？

一直做java的，现在想做区块链跟web3开发，golang要一般网站开发能力、im、还有dapp这种把

**Comment by hele204** [comment]
哎呀老哥,我也是Java的,想学go

**Comment by zc2638** [comment]
> 一直做java的，现在想做区块链跟web3开发，golang要一般网站开发能力、im、还有dapp这种把

往区块链方向，可以看看对应的技术栈框架之类的，istio更偏向云，需要具备一些 docker、k8s、envoy 的知识储备
