### ISSUE TITLE
找不到Cookie

### ISSUE THREAD

**Issue by Xtay-YX** [zc2638/ddshop#5]
老哥,我找不到那两个网址的包. 
电脑端安装了证书,放到了受信任的根目录下.  而且打开的PC的微信叮咚买菜小程序>
抓包工具中没有显示那两个网址.

**Comment by zc2638** [comment]
根据 `ddxq.mobi` 过滤出抓的请求，随便找个接口应该都有 cookie

**Comment by Xtay-YX** [comment]
第一次用抓包工具,抓到了.
老哥,具体哪个是cookie呀

**Comment by zc2638** [comment]
README中有写哦，先看一下。
https://github.com/zc2638/ddshop#%E4%BD%BF%E7%94%A8

Cookie Key 为 DDXQSESSID
