### ISSUE TITLE
全选购物车商品失败

### ISSUE THREAD

**Issue by SLtudou4** [zc2638/ddshop#50]
![image](https://user-images.githubusercontent.com/17898186/163744677-cec38303-10ab-4318-9c2d-0d0c6f296b2f.png)
请问直接运行exe一直提示这个错误如何解决呢

**Comment by zc2638** [comment]
如果是 app 的 cookie，配置文件中的 channel 配置为 3  
如果是小程序的 cookie，channel配置为 4

**Comment by SLtudou4** [comment]
我直接cmd运行的，如下，
ddshop_windows_amd64.exe --cookie xxxx
请问下channel如何配置呢

**Comment by zc2638** [comment]
看下README，要先创建配置文件

**Comment by SLtudou4** [comment]
已解决，谢谢；
go run main.go --config "本地地址+\ddshop-main\config\config.yaml"
