### ISSUE TITLE
docker运行，能发出通知来吗？

### ISSUE THREAD

**Issue by ypzhuang** [zc2638/ddshop#51]
我这边报以下错误，没声卡支持？

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
WARNING[2022/04/19 11:35:54] 通知失败: Music: oto: ALSA error: No such file or directory

**Comment by zc2638** [comment]
参考：https://qa.1r1g.com/sf/ask/2029000011/
需要将声卡设备挂载到docker容器中
