### ISSUE TITLE
ddshop不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by chenshi1324** [zc2638/ddshop#55]
![image](https://user-images.githubusercontent.com/60893309/164361709-5d0c09cf-9056-4f7b-8b36-0969a36501b7.png)

这个要怎么解决

**Comment by ares0x** [comment]
进入到ddshop所在的文件位置执行命令或者将ddshop所在位置添加到环境变量中执行

**Comment by chenshi1324** [comment]
> 进入ddshop所在的文件位置执行命令或将ddshop所在的环境变量中执行位置

![image](https://user-images.githubusercontent.com/60893309/164366043-ab7e42af-abc4-4b6f-ac01-8c8eb21df6cb.png)
是在ddshop所在的文件位置执行命令的 并且也加了一个环境变量

**Comment by ares0x** [comment]
win下执行应该要加文件类型吧，把.exe加上试一下？

**Comment by ares0x** [comment]
你的可执行文件的文件名不是ddshop，是ddshop_windows_amd64.exe

**Comment by chenshi1324** [comment]
> 
谢谢 解决了  把名字改成了ddshop.exe

**Comment by ares0x** [comment]
不客气
