### ISSUE TITLE
无法获取购物车中商品

### ISSUE THREAD

**Issue by z3y3** [zc2638/ddshop#57]
INFO   [2022/04/29 14:09:00] =====> 获取购物车中有效商品
ERROR  [2022/04/29 14:09:00] statusCode: 405, body: {"error":"AssertError","code":"405","data":"-405"}
ERROR  [2022/04/29 14:09:00] 执行出错: statusCode: 405, body: {"error":"AssertError","code":"405","data":"-405"}
WARNING[2022/04/29 14:09:00] 将在 100ms 后继续执行

是叮咚更新接口了吗？

**Comment by jasonyzi** [comment]
是你被封了

**Comment by z3y3** [comment]
app上可以下单啊

**Comment by zc2638** [comment]
可能是增加了签名，这部分之前没有做处理
