### ISSUE TITLE
商品信息有变化    错误

### ISSUE THREAD

**Issue by cqzhong** [zc2638/ddshop#6]
INFO   [2022/04/11 18:14:38] >>> 生成订单信息                                   
ERROR  [2022/04/11 18:14:38] 检查订单失败: parse response failed: { 	"code": 5013, 	"msg": "当前下单人数过多，请稍后再试！", 	"success": false, 	"data": {} }

**Comment by zc2638** [comment]
是否可以描述的更详细一些

**Comment by cqzhong** [comment]
INFO   [2022/04/11 18:30:57] >>> 获取购物车中有效商品                               
INFO   [2022/04/11 18:30:57] [0] 手擀式面 300g/袋 数量：6 总价：21.00                
INFO   [2022/04/11 18:30:57] >>> 生成订单信息                                   
INFO   [2022/04/11 18:30:57] 订单总金额：26.00                                  
INFO   [2022/04/11 18:30:57] >>> 获取可预约时间                                  
INFO   [2022/04/11 18:30:57] 发现可用的配送时段!                                   
INFO   [2022/04/11 18:30:57] >>> 提交订单中                                    
ERROR  [2022/04/11 18:30:58] 商品信息有变化

**Comment by cqzhong** [comment]
不好意思，可以了。菜得加购邮费的

**Comment by haifengzuishuai** [comment]
抢到了吗
