### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by haifengzuishuai** [zc2638/ddshop#8]
WARNING[2022/04/12 06:00:56] 提交订单失败: 无法识别的返回码: -3001, msg:
INFO   [2022/04/12 06:00:56] >>> 提交订单中
WARNING[2022/04/12 06:00:56] 提交订单失败: 无法识别的返回码: -3001, msg:
INFO   [2022/04/12 06:00:56] >>> 提交订单中
WARNING[2022/04/12 06:00:56] 提交订单失败: 无法识别的返回码: -3001, msg:
INFO   [2022/04/12 06:00:56] >>> 提交订单中
WARNING[2022/04/12 06:00:58] 提交订单失败: 无法识别的返回码: 1, msg: 参数错误
INFO   [2022/04/12 06:00:58] >>> 提交订单中
WARNING[2022/04/12 06:00:58] 提交订单失败: 无法识别的返回码: -3001, msg:
INFO   [2022/04/12 06:00:58] >>> 提交订单中
WARNING[2022/04/12 06:00:58] 提交订单失败: 无法识别的返回码: -3001, msg:
INFO   [2022/04/12 06:00:58] >>> 提交订单中

**Comment by zijianziye** [comment]
我也是这个问题，没抢到，不知道是不是选择时间段的问题

**Comment by Tuangtuang** [comment]
+1

**Comment by lycohehe** [comment]
+1

**Comment by dhbowen1** [comment]
一样的问题

**Comment by lsl233** [comment]
+1
顺便问问，不是上海的ip可以抢吗

**Comment by wenbin2017** [comment]
同问

**Comment by haifengzuishuai** [comment]
> 

我理解可以。因为根据站点下单，和ip没关系

**Comment by zijianziye** [comment]
坐等大佬过来修复了，不过现在是真的难抢，开了也要看运气

**Comment by castoner** [comment]
我也是这个问题，难受哦

**Comment by castoner** [comment]
伙计们，大佬的程序没问题，还是可以抢到的，多试几次就行了

**Comment by dhbowen1** [comment]
> 伙计们，大佬的程序没问题，还是可以抢到的，多试几次就行了

你抢到了？没报错？

**Comment by castoner** [comment]
> > 伙计们，大佬的程序没问题，还是可以抢到的，多试几次就行了
> 
> 你抢到了？没报错？

一样的日志消息，但是下单成功了
![image](https://user-images.githubusercontent.com/17471440/162858310-fe30075c-3ab1-44a9-b4f6-1c555ef037bc.png)

**Comment by githubw2015** [comment]
我改了每秒钟提交订单 100次，都没刷到，6点，8点半都试过了，报
{
    "success": false,
    "code": -3001,
    "msg": "",
    "tips": {
        "duration": 400,
        "limitMsg": "前方拥挤，请稍后再试..."
    },
    "data": {}
}

**Comment by dhbowen1** [comment]
> > > 伙计们，大佬的程序没问题，还是可以抢到的，多试几次就行了
> > 
> > 
> > 你抢到了？没报错？
> 
> 一样的日志消息，但是下单成功了 ![image](https://user-images.githubusercontent.com/17471440/162858310-fe30075c-3ab1-44a9-b4f6-1c555ef037bc.png)

我看一直报错，关了

**Comment by dhbowen1** [comment]
> 我改了每秒钟提交订单 100次，都没刷到，6点，8点半都试过了，报 { "success": false, "code": -3001, "msg": "", "tips": { "duration": 400, "limitMsg": "前方拥挤，请稍后再试..." }, "data": {} }

刷的太快当心封号

**Comment by githubw2015** [comment]
> 
刷太快都没成功过，说明接口已经做了限制了。

**Comment by haifengzuishuai** [comment]
> > > 伙计们，大佬的程序没问题，还是可以抢到的，多试几次就行了
> > 
> > 
> > 你抢到了？没报错？
> 
> 一样的日志消息，但是下单成功了 ![image](https://user-images.githubusercontent.com/17471440/162858310-fe30075c-3ab1-44a9-b4f6-1c555ef037bc.png)

就是你的日志里也报这个错，但还是下单成功了是吗

**Comment by zc2638** [comment]
- 增加 同时对所有可预约时间段发起请求，提高成功率
- 增加 连续请求的时间间隔(ms)，防止被封控，支持自定义

**Comment by dhbowen1** [comment]
> * 增加 同时对所有可预约时间段发起请求，提高成功率
> * 增加 连续请求的时间间隔(ms)，防止被封控，支持自定义

是啊，现在根本不用考虑时段，只要能派送都可以

**Comment by coldtea07** [comment]
想问下这个好像不用输入自己的ddmc-uid， 没有这个只有cookie可以成功下单吗

**Comment by zc2638** [comment]
程序会通过 cookie 获取用户uid，然后自动设置 @coldtea07

**Comment by nickww520** [comment]
> > > 伙计们，大佬的程序没问题，还是可以抢到的，多试几次就行了
> > 
> > 
> > 你抢到了？没报错？
> 
> 一样的日志消息，但是下单成功了 ![image](https://user-images.githubusercontent.com/17471440/162858310-fe30075c-3ab1-44a9-b4f6-1c555ef037bc.png)

大佬，能教教我怎么使用运行这个脚本吗？ 一脸懵逼中

**Comment by zc2638** [comment]
@nickww520 拿到cookie之后，看仓库的README，执行命令替换 `<custom-cookie>` 即可

**Comment by nickww520** [comment]
> @nickww520 拿到cookie之后，看仓库的README，执行命令替换 `<custom-cookie>` 即可

我意思是用什么工具来执行这个脚本啊？ github上的脚本我到现在一个都没有执行成功过，不会玩，有没有相关视频教程地址，推荐下，我自己看也可以，要么麻烦你和我说下也行，感谢大侠！

**Comment by zc2638** [comment]
README上都有写哈！  
抓包拿cookie的话，参考https://github.com/zc2638/ddshop#%E6%8A%93%E5%8C%85  
本抢购程序的话，可以直接在这里下载https://github.com/zc2638/ddshop/releases

**Comment by nickww520** [comment]
> README上都有写哈！ 抓包拿cookie的话，参考https://github.com/zc2638/ddshop#%E6%8A%93%E5%8C%85 本抢购程序的话，可以直接在这里下载https://github.com/zc2638/ddshop/releases

运行工具打开就提示这个然后就自动关闭了
This is a command line tool.
You need to open cmd.exe and run it from there.

**Comment by zc2638** [comment]
@nickww520 参考 #4

**Comment by nickww520** [comment]
> @nickww520 参考 #4

运行起来了，感谢，还有个问题，8秒后重试，这个重试时间怎么修改？ 还有1秒提交100次哪里修改啊？

**Comment by zc2638** [comment]
@nickww520 这个时间暂时不支持修改
