### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by 77742541** [zc2638/ddshop#9]
cookie抓到了,老哥能详细说一下怎样在脚本中设置 的嘛

**Comment by zc2638** [comment]
README中有写哦，先看一下。
https://github.com/zc2638/ddshop#%E4%BD%BF%E7%94%A8

**Comment by 77742541** [comment]
我直接在vscode的终端里运行ddshop --cookie <自定义cookie >这个命令一直提示错误
